apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: dev
spec:
  selector:
    matchLabels:
      app: app1
  replicas: 1
  template:
    metadata:
      labels:
        app: app1
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - examina-prod
            topologyKey: "kubernetes.io/hostname"
      tolerations:
      - key: "taint1"
        operator: "Equal"
        value: "examina-prod"
        effect: "NoSchedule"
      containers:
      - name: app1
        image: ubuntu:app1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: app1
          mountPath: /var/www/html/app1
        - name: examina-upload
          mountPath: /var/www/html/app1
        resources:
          requests:
            memory: "512Mi"
            cpu: "50m"
          limits:
            memory: "1.5Gi"
            cpu: "400m"
      nodeSelector:
        app: dev
      imagePullSecrets:
        - name: cred
      volumes:
      - hostPath:
          path: "/mnt/app1"
        name: app1
      - hostPath:
          path: "/mnt/app1"
        name: app1
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: app1
  namespace: dev
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31082
    protocol: TCP
    name: app1
  selector:
    app: app1
